services:                                  # Nhóm dịch vụ
  redis:
      image: redis:7-alpine
      # Nếu muốn bật password:
      # command: ["redis-server", "--requirepass", "mysecret"]
      ports:
        - "6379:6379"   # tùy, chỉ cần khi muốn truy cập từ host
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 2s
        timeout: 1s
        retries: 20
      
      
  mongo:                                   # MongoDB
    image: mongo:7                         # Image Mongo v7
    environment:                           # Biến môi trường khởi tạo
      MONGO_INITDB_ROOT_USERNAME: root     # User root
      MONGO_INITDB_ROOT_PASSWORD: secret   # Mật khẩu root
    ports:
      - "27017:27017"                      # Mở cổng 27017 ra host
    volumes:
      - mongo_data:/data/db                # Lưu dữ liệu Mongo vào named volume

  api:                                     # Ứng dụng Node.js
    build:
      context: .                           # Build từ thư mục hiện tại
      target: dev                          # Dùng stage "dev" trong Dockerfile
    environment:
      PORT: ${PORT:-3000}                  # Port của app (mặc định 3000)
      NODE_ENV: development                # Chế độ development
      MONGO_URL: ${MONGO_URL:-mongodb://root:secret@mongo:27017/dev?authSource=admin}  # Kết nối Mongo qua service "mongo"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"      # Map cổng host:container
      - "9229:9229"
    volumes:
      - ./:/app                            # Bind mã nguồn host vào /app (hot-reload)
    depends_on: [mongo]                    # Khởi động sau mongo (chỉ đảm bảo thứ tự)
    command: npm run dev                   # Lệnh chạy dev (ví dụ nodemon)
    restart: unless-stopped

volumes:
  mongo_data: {}                           # Khai báo named volume cho Mongo
