services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      target: runner              
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL:-mongodb://root:secret@mongo:27017/devcamper?authSource=admin}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on: [mongo]
    restart: unless-stopped       # tự khởi động lại nếu crash
    # ❌ KHÔNG bind mount code, KHÔNG dùng npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start            # dùng CMD của image

volumes:
  mongo_data: {}
